spring.application.name=staysync-api-gateway

server.port=8080


# =========================================
# Eureka Client
# =========================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# =========================================
# Spring Cloud Gateway
# =========================================

spring.cloud.gateway.server.webflux.enabled=true


# =========================================
# Room Service Route
# =========================================

spring.cloud.gateway.server.webflux.routes[0].id=room-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://STAYSYNC-ROOM-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/staysync-room-service/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1


# =========================================
# Booking Service Route
# =========================================

spring.cloud.gateway.server.webflux.routes[1].id=booking-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://STAYSYNC-BOOKING-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/staysync-booking-service/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1


# =========================================
# Auth Service Route
# =========================================

spring.cloud.gateway.server.webflux.routes[2].id=auth-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://STAYSYNC-AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/staysync-auth-service/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=1


# =========================================
# JWT
# =========================================

jwt.secret=${JWT_SECRET:StaySync-development-secret-change-this-before-production-2026}


# =========================================
# Actuator
# =========================================

management.endpoint.gateway.access=read-only
management.endpoints.web.exposure.include=health,info,gateway