spring.application.name=staysync-auth-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/staysync
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=health,info

jwt.secret=${JWT_SECRET:StaySync-development-secret-change-this-before-production-2026}
jwt.expiration=86400000